// Customizable Area Start
import MergeEngineUtilities from "./MergeEngineUtilities";
import {StyleSheet} from 'react-native'

const global_styles = StyleSheet.create({
    attrbuted_SUBTITLE1COLORSTYLEText10: {
        position: "relative",
        width: MergeEngineUtilities.deviceBasedDynamicDimension(224, true, 1),
        height: MergeEngineUtilities.deviceBasedDynamicDimension(24, false, 1),
        marginLeft: MergeEngineUtilities.deviceBasedDynamicDimension(24, true, 1),
        marginTop: MergeEngineUtilities.deviceBasedDynamicDimension(16, false, 1),
        opacity: 1,
        backgroundColor: "transparent",
        fontStyle: "normal",
        fontWeight: "normal",
        includeFontPadding: false,
        padding: MergeEngineUtilities.deviceBasedDynamicDimension(0, true, 1),
        color: "rgba(53, 56, 72, 1)",
        textAlign: "left",
        textAlignVertical: "top",
        fontFamily: "",
        fontSize: MergeEngineUtilities.deviceBasedDynamicDimension(16, true, 1),
    },
    textlabel_SelectMediaHouseText: {
        position: "absolute",
        width: MergeEngineUtilities.deviceBasedDynamicDimension(137, true, 1),
        height: MergeEngineUtilities.deviceBasedDynamicDimension(20, false, 1),
        marginLeft: MergeEngineUtilities.deviceBasedDynamicDimension(24, true, 1),
        marginTop: MergeEngineUtilities.deviceBasedDynamicDimension(554, false, 1),
        opacity: 1,
        backgroundColor: "transparent",
        fontStyle: "normal",
        fontWeight: "normal",
        includeFontPadding: false,
        padding: MergeEngineUtilities.deviceBasedDynamicDimension(0, true, 1),
        color: "rgba(53, 56, 72, 1)",
        textAlign: "left",
        textAlignVertical: "top",
        fontFamily: "Poppins-Regular",
        fontSize: MergeEngineUtilities.deviceBasedDynamicDimension(14, true, 1),
    },
    attrbuted_textlabel_SelectRegionYouInText: {
        position: "relative",
        width: MergeEngineUtilities.deviceBasedDynamicDimension(197, true, 1),
        height: MergeEngineUtilities.deviceBasedDynamicDimension(17, false, 1),
        marginLeft: MergeEngineUtilities.deviceBasedDynamicDimension(0, true, 1),
        marginTop: MergeEngineUtilities.deviceBasedDynamicDimension(0, false, 1),
        opacity: 1,
        backgroundColor: "transparent",
        fontStyle: "normal",
        fontWeight: "normal",
        includeFontPadding: false,
        padding: MergeEngineUtilities.deviceBasedDynamicDimension(0, true, 1),
        color: "rgba(53, 56, 72, 1)",
        textAlign: "left",
        textAlignVertical: "top",
        fontFamily: "",
        fontSize: MergeEngineUtilities.deviceBasedDynamicDimension(14, true, 1),
    },
    TEXTCOLORSTYLEText: {
        position: "absolute",
        width: MergeEngineUtilities.deviceBasedDynamicDimension(64, true, 3.5625),
        height: MergeEngineUtilities.deviceBasedDynamicDimension(16, false, 1.5555555555555556),
        marginLeft: MergeEngineUtilities.deviceBasedDynamicDimension(16, true, 3.5625),
        marginTop: MergeEngineUtilities.deviceBasedDynamicDimension(10, false, 1.5555555555555556),
        opacity: 1,
        backgroundColor: "transparent",
        fontStyle: "normal",
        fontWeight: "normal",
        includeFontPadding: false,
        padding: MergeEngineUtilities.deviceBasedDynamicDimension(0, true, 1),
        color: "rgba(255, 255, 255, 1)",
        textAlign: "center",
        textAlignVertical: "top",
        fontFamily: "AirbnbCerealApp-Medium",
        fontSize: MergeEngineUtilities.deviceBasedDynamicDimension(16, true, 1),
    },
    group_GroupGroup: {
        position: "absolute",
        width: MergeEngineUtilities.deviceBasedDynamicDimension(343, true, 1),
        height: MergeEngineUtilities.deviceBasedDynamicDimension(82, false, 1),
        marginLeft: MergeEngineUtilities.deviceBasedDynamicDimension(24, true, 1),
        marginTop: MergeEngineUtilities.deviceBasedDynamicDimension(234, false, 1),
        opacity: 1,
        borderRadius: MergeEngineUtilities.deviceBasedDynamicDimension(0, true, 1),
        borderWidth: MergeEngineUtilities.deviceBasedDynamicDimension(0, true, 1),
    },
    attrbuted_SUBTITLE1COLORSTYLEText11: {
        position: "relative",
        width: MergeEngineUtilities.deviceBasedDynamicDimension(81, true, 1),
        height: MergeEngineUtilities.deviceBasedDynamicDimension(26, false, 1),
        marginLeft: MergeEngineUtilities.deviceBasedDynamicDimension(12, true, 1),
        marginTop: MergeEngineUtilities.deviceBasedDynamicDimension(8, false, 1),
        opacity: 1,
        backgroundColor: "transparent",
        fontStyle: "normal",
        fontWeight: "normal",
        includeFontPadding: false,
        padding: MergeEngineUtilities.deviceBasedDynamicDimension(0, true, 1),
        color: "rgba(53, 56, 72, 1)",
        textAlign: "left",
        textAlignVertical: "top",
        fontFamily: "",
        fontSize: MergeEngineUtilities.deviceBasedDynamicDimension(14, true, 1),
    },
    textinput_TextFieldFilledLeadingIconNoAssistiveTextRestingWithIconSmallCopy3TxtInput: {
        position: "absolute",
        width: MergeEngineUtilities.deviceBasedDynamicDimension(115, true, 1),
        height: MergeEngineUtilities.deviceBasedDynamicDimension(40, false, 1),
        marginLeft: MergeEngineUtilities.deviceBasedDynamicDimension(24, true, 1),
        marginTop: MergeEngineUtilities.deviceBasedDynamicDimension(808, false, 1),
        opacity: 1,
        borderRadius: MergeEngineUtilities.deviceBasedDynamicDimension(8, true, 1),
        backgroundColor: "rgba(255, 255, 255, 1)",
    },
    attrbuted_textlabel_SignInText: {
        position: "relative",
        width: MergeEngineUtilities.deviceBasedDynamicDimension(101, true, 1),
        height: MergeEngineUtilities.deviceBasedDynamicDimension(39, false, 1),
        marginLeft: MergeEngineUtilities.deviceBasedDynamicDimension(144, true, 1),
        marginTop: MergeEngineUtilities.deviceBasedDynamicDimension(263, false, 1),
        opacity: 1,
        backgroundColor: "transparent",
        fontStyle: "normal",
        fontWeight: "normal",
        includeFontPadding: false,
        padding: MergeEngineUtilities.deviceBasedDynamicDimension(0, true, 1),
        color: "rgba(31, 69, 252, 1)",
        textAlign: "center",
        textAlignVertical: "top",
        fontFamily: "Poppins-Medium",
        fontSize: MergeEngineUtilities.deviceBasedDynamicDimension(28, true, 1),
    },
    attrbuted_textlabel_ChangePasswordText: {
        position: "relative",
        width: MergeEngineUtilities.deviceBasedDynamicDimension(224, true, 1),
        height: MergeEngineUtilities.deviceBasedDynamicDimension(36, false, 1),
        marginLeft: MergeEngineUtilities.deviceBasedDynamicDimension(56, true, 1),
        marginTop: MergeEngineUtilities.deviceBasedDynamicDimension(69, false, 1),
        opacity: 1,
        backgroundColor: "transparent",
        fontStyle: "normal",
        fontWeight: "bold",
        includeFontPadding: false,
        padding: MergeEngineUtilities.deviceBasedDynamicDimension(0, true, 1),
        color: "rgba(17, 21, 28, 1)",
        textAlign: "left",
        textAlignVertical: "top",
        fontFamily: "Poppins-SemiBold",
        fontSize: MergeEngineUtilities.deviceBasedDynamicDimension(24, true, 1),
    },
    attrbuted_textlabel_OptionalText: {
        position: "relative",
        width: MergeEngineUtilities.deviceBasedDynamicDimension(63, true, 1),
        height: MergeEngineUtilities.deviceBasedDynamicDimension(17, false, 1),
        marginLeft: MergeEngineUtilities.deviceBasedDynamicDimension(282, true, 1),
        marginTop: MergeEngineUtilities.deviceBasedDynamicDimension(412, false, 1),
        opacity: 1,
        backgroundColor: "transparent",
        fontStyle: "normal",
        fontWeight: "normal",
        includeFontPadding: false,
        padding: MergeEngineUtilities.deviceBasedDynamicDimension(0, true, 1),
        color: "rgba(190, 192, 201, 1)",
        textAlign: "center",
        textAlignVertical: "top",
        fontFamily: "",
        fontSize: MergeEngineUtilities.deviceBasedDynamicDimension(14, true, 1),
    },
    SUBTITLE1COLORSTYLEText12: {
        position: "absolute",
        width: MergeEngineUtilities.deviceBasedDynamicDimension(81, true, 0.8344827586206897),
        height: MergeEngineUtilities.deviceBasedDynamicDimension(26, false, 1),
        marginLeft: MergeEngineUtilities.deviceBasedDynamicDimension(12, true, 0.8344827586206897),
        marginTop: MergeEngineUtilities.deviceBasedDynamicDimension(8, false, 1),
        opacity: 1,
        backgroundColor: "transparent",
        fontStyle: "normal",
        fontWeight: "normal",
        includeFontPadding: false,
        padding: MergeEngineUtilities.deviceBasedDynamicDimension(0, true, 1),
        color: "rgba(53, 56, 72, 1)",
        textAlign: "left",
        textAlignVertical: "top",
        fontFamily: "",
        fontSize: MergeEngineUtilities.deviceBasedDynamicDimension(14, true, 1),
    },
    attrbuted_SUBTITLE1COLORSTYLEText16: {
        position: "relative",
        width: MergeEngineUtilities.deviceBasedDynamicDimension(81, true, 1),
        height: MergeEngineUtilities.deviceBasedDynamicDimension(26, false, 1),
        marginLeft: MergeEngineUtilities.deviceBasedDynamicDimension(12, true, 1),
        marginTop: MergeEngineUtilities.deviceBasedDynamicDimension(8, false, 1),
        opacity: 1,
        backgroundColor: "transparent",
        fontStyle: "normal",
        fontWeight: "normal",
        includeFontPadding: false,
        padding: MergeEngineUtilities.deviceBasedDynamicDimension(0, true, 1),
        color: "rgba(53, 56, 72, 1)",
        textAlign: "left",
        textAlignVertical: "top",
        fontFamily: "",
        fontSize: MergeEngineUtilities.deviceBasedDynamicDimension(14, true, 1),
    },
    textinput_TextFieldFilledLeadingIconNoAssistiveTextRestingWithIconSmallCopyCopy4TxtInput: {
        position: "absolute",
        width: MergeEngineUtilities.deviceBasedDynamicDimension(96, true, 1),
        height: MergeEngineUtilities.deviceBasedDynamicDimension(40, false, 1),
        marginLeft: MergeEngineUtilities.deviceBasedDynamicDimension(152, true, 1),
        marginTop: MergeEngineUtilities.deviceBasedDynamicDimension(808, false, 1),
        opacity: 1,
        borderRadius: MergeEngineUtilities.deviceBasedDynamicDimension(8, true, 1),
        backgroundColor: "rgba(255, 255, 255, 1)",
    },
    textinput_TextFieldFilledLeadingIconNoAssistiveTextRestingWithIconSmallCopy2TxtInput: {
        position: "absolute",
        width: MergeEngineUtilities.deviceBasedDynamicDimension(90, true, 1),
        height: MergeEngineUtilities.deviceBasedDynamicDimension(40, false, 1),
        marginLeft: MergeEngineUtilities.deviceBasedDynamicDimension(24, true, 1),
        marginTop: MergeEngineUtilities.deviceBasedDynamicDimension(648, false, 1),
        opacity: 1,
        borderRadius: MergeEngineUtilities.deviceBasedDynamicDimension(8, true, 1),
        backgroundColor: "rgba(255, 255, 255, 1)",
    },
    SUBTITLE1COLORSTYLEText7: {
        position: "absolute",
        width: MergeEngineUtilities.deviceBasedDynamicDimension(224, true, 1.0426829268292683),
        height: MergeEngineUtilities.deviceBasedDynamicDimension(24, false, 1),
        marginLeft: MergeEngineUtilities.deviceBasedDynamicDimension(24, true, 1.0426829268292683),
        marginTop: MergeEngineUtilities.deviceBasedDynamicDimension(16, false, 1),
        opacity: 1,
        backgroundColor: "transparent",
        fontStyle: "normal",
        fontWeight: "normal",
        includeFontPadding: false,
        padding: MergeEngineUtilities.deviceBasedDynamicDimension(0, true, 1),
        color: "rgba(53, 56, 72, 1)",
        textAlign: "left",
        textAlignVertical: "top",
        fontFamily: "",
        fontSize: MergeEngineUtilities.deviceBasedDynamicDimension(16, true, 1),
    },
    textlabel_SelectRegionYouInText: {
        position: "relative",
        width: MergeEngineUtilities.deviceBasedDynamicDimension(197, true, 1),
        height: MergeEngineUtilities.deviceBasedDynamicDimension(17, false, 1),
        marginLeft: MergeEngineUtilities.deviceBasedDynamicDimension(0, true, 1),
        marginTop: MergeEngineUtilities.deviceBasedDynamicDimension(0, false, 1),
        opacity: 1,
        backgroundColor: "transparent",
        fontStyle: "normal",
        fontWeight: "normal",
        includeFontPadding: false,
        padding: MergeEngineUtilities.deviceBasedDynamicDimension(0, true, 1),
        color: "rgba(53, 56, 72, 1)",
        textAlign: "left",
        textAlignVertical: "top",
        fontFamily: "",
        fontSize: MergeEngineUtilities.deviceBasedDynamicDimension(14, true, 1),
    },
    attrbuted_SUBTITLE1COLORSTYLEText9: {
        position: "relative",
        width: MergeEngineUtilities.deviceBasedDynamicDimension(81, true, 1),
        height: MergeEngineUtilities.deviceBasedDynamicDimension(26, false, 1),
        marginLeft: MergeEngineUtilities.deviceBasedDynamicDimension(12, true, 1),
        marginTop: MergeEngineUtilities.deviceBasedDynamicDimension(8, false, 1),
        opacity: 1,
        backgroundColor: "transparent",
        fontStyle: "normal",
        fontWeight: "normal",
        includeFontPadding: false,
        padding: MergeEngineUtilities.deviceBasedDynamicDimension(0, true, 1),
        color: "rgba(53, 56, 72, 1)",
        textAlign: "left",
        textAlignVertical: "top",
        fontFamily: "",
        fontSize: MergeEngineUtilities.deviceBasedDynamicDimension(14, true, 1),
    },
    textinput_TextFieldFilledLeadingIconNoAssistiveTextRestingWithIconSmallCopyCopy5TxtInput: {
        position: "absolute",
        width: MergeEngineUtilities.deviceBasedDynamicDimension(108, true, 1),
        height: MergeEngineUtilities.deviceBasedDynamicDimension(40, false, 1),
        marginLeft: MergeEngineUtilities.deviceBasedDynamicDimension(261, true, 1),
        marginTop: MergeEngineUtilities.deviceBasedDynamicDimension(808, false, 1),
        opacity: 1,
        borderRadius: MergeEngineUtilities.deviceBasedDynamicDimension(8, true, 1),
        backgroundColor: "rgba(255, 255, 255, 1)",
    },
    textinput_TextFieldFilledLeadingIconNoAssistiveTextRestingCopy5TxtInput: {
        position: "absolute",
        width: MergeEngineUtilities.deviceBasedDynamicDimension(342, true, 1),
        height: MergeEngineUtilities.deviceBasedDynamicDimension(56, false, 1),
        marginLeft: MergeEngineUtilities.deviceBasedDynamicDimension(24, true, 1),
        marginTop: MergeEngineUtilities.deviceBasedDynamicDimension(580, false, 1),
        opacity: 1,
        borderRadius: MergeEngineUtilities.deviceBasedDynamicDimension(8, true, 1),
        backgroundColor: "rgba(255, 255, 255, 1)",
    },
    attrbuted_SUBTITLE1COLORSTYLEText15: {
        position: "relative",
        width: MergeEngineUtilities.deviceBasedDynamicDimension(81, true, 1),
        height: MergeEngineUtilities.deviceBasedDynamicDimension(26, false, 1),
        marginLeft: MergeEngineUtilities.deviceBasedDynamicDimension(12, true, 1),
        marginTop: MergeEngineUtilities.deviceBasedDynamicDimension(8, false, 1),
        opacity: 1,
        backgroundColor: "transparent",
        fontStyle: "normal",
        fontWeight: "normal",
        includeFontPadding: false,
        padding: MergeEngineUtilities.deviceBasedDynamicDimension(0, true, 1),
        color: "rgba(53, 56, 72, 1)",
        textAlign: "left",
        textAlignVertical: "top",
        fontFamily: "",
        fontSize: MergeEngineUtilities.deviceBasedDynamicDimension(14, true, 1),
    },
    attrbuted_textlabel_SelectCategoriesCopyText: {
        position: "relative",
        width: MergeEngineUtilities.deviceBasedDynamicDimension(115, true, 1),
        height: MergeEngineUtilities.deviceBasedDynamicDimension(17, false, 1),
        marginLeft: MergeEngineUtilities.deviceBasedDynamicDimension(24, true, 1),
        marginTop: MergeEngineUtilities.deviceBasedDynamicDimension(714, false, 1),
        opacity: 1,
        backgroundColor: "transparent",
        fontStyle: "normal",
        fontWeight: "normal",
        includeFontPadding: false,
        padding: MergeEngineUtilities.deviceBasedDynamicDimension(0, true, 1),
        color: "rgba(53, 56, 72, 1)",
        textAlign: "left",
        textAlignVertical: "top",
        fontFamily: "",
        fontSize: MergeEngineUtilities.deviceBasedDynamicDimension(14, true, 1),
    },
    textinput_TextFieldFilledLeadingIconNoAssistiveTextRestingWithIconSmallTxtInput2: {
        position: "absolute",
        width: MergeEngineUtilities.deviceBasedDynamicDimension(115, true, 1),
        height: MergeEngineUtilities.deviceBasedDynamicDimension(40, false, 1),
        marginLeft: MergeEngineUtilities.deviceBasedDynamicDimension(24, true, 1),
        marginTop: MergeEngineUtilities.deviceBasedDynamicDimension(328, false, 1),
        opacity: 1,
        borderRadius: MergeEngineUtilities.deviceBasedDynamicDimension(8, true, 1),
        backgroundColor: "rgba(255, 255, 255, 1)",
    },
    attrbuted_textlabel_DonthaveanaccounText3: {
        position: "relative",
        width: MergeEngineUtilities.deviceBasedDynamicDimension(252, true, 1),
        height: MergeEngineUtilities.deviceBasedDynamicDimension(22, false, 1),
        marginLeft: MergeEngineUtilities.deviceBasedDynamicDimension(69, true, 1),
        marginTop: MergeEngineUtilities.deviceBasedDynamicDimension(790, false, 1),
        opacity: 1,
        backgroundColor: "transparent",
        fontStyle: "normal",
        fontWeight: "normal",
        includeFontPadding: false,
        padding: MergeEngineUtilities.deviceBasedDynamicDimension(0, true, 1),
        color: "rgba(31, 69, 252, 1)",
        textAlign: "center",
        textAlignVertical: "top",
        fontFamily: "Poppins-Medium",
        fontSize: MergeEngineUtilities.deviceBasedDynamicDimension(14, true, 1),
    },
    textlabel_OptionalText: {
        position: "absolute",
        width: MergeEngineUtilities.deviceBasedDynamicDimension(63, true, 1),
        height: MergeEngineUtilities.deviceBasedDynamicDimension(17, false, 1),
        marginLeft: MergeEngineUtilities.deviceBasedDynamicDimension(282, true, 1),
        marginTop: MergeEngineUtilities.deviceBasedDynamicDimension(412, false, 1),
        opacity: 1,
        backgroundColor: "transparent",
        fontStyle: "normal",
        fontWeight: "normal",
        includeFontPadding: false,
        padding: MergeEngineUtilities.deviceBasedDynamicDimension(0, true, 1),
        color: "rgba(190, 192, 201, 1)",
        textAlign: "center",
        textAlignVertical: "top",
        fontFamily: "",
        fontSize: MergeEngineUtilities.deviceBasedDynamicDimension(14, true, 1),
    },
    attrbuted_textlabel_SelectLanguageText: {
        position: "relative",
        width: MergeEngineUtilities.deviceBasedDynamicDimension(104, true, 1),
        height: MergeEngineUtilities.deviceBasedDynamicDimension(17, false, 1),
        marginLeft: MergeEngineUtilities.deviceBasedDynamicDimension(24, true, 1),
        marginTop: MergeEngineUtilities.deviceBasedDynamicDimension(394, false, 1),
        opacity: 1,
        backgroundColor: "transparent",
        fontStyle: "normal",
        fontWeight: "normal",
        includeFontPadding: false,
        padding: MergeEngineUtilities.deviceBasedDynamicDimension(0, true, 1),
        color: "rgba(53, 56, 72, 1)",
        textAlign: "left",
        textAlignVertical: "top",
        fontFamily: "",
        fontSize: MergeEngineUtilities.deviceBasedDynamicDimension(14, true, 1),
    },
    SUBTITLE1COLORSTYLEText15: {
        position: "absolute",
        width: MergeEngineUtilities.deviceBasedDynamicDimension(81, true, 0.6620689655172414),
        height: MergeEngineUtilities.deviceBasedDynamicDimension(26, false, 1),
        marginLeft: MergeEngineUtilities.deviceBasedDynamicDimension(12, true, 0.6620689655172414),
        marginTop: MergeEngineUtilities.deviceBasedDynamicDimension(8, false, 1),
        opacity: 1,
        backgroundColor: "transparent",
        fontStyle: "normal",
        fontWeight: "normal",
        includeFontPadding: false,
        padding: MergeEngineUtilities.deviceBasedDynamicDimension(0, true, 1),
        color: "rgba(53, 56, 72, 1)",
        textAlign: "left",
        textAlignVertical: "top",
        fontFamily: "",
        fontSize: MergeEngineUtilities.deviceBasedDynamicDimension(14, true, 1),
    },
    attrbuted_SUBTITLE1COLORSTYLEText12: {
        position: "relative",
        width: MergeEngineUtilities.deviceBasedDynamicDimension(81, true, 1),
        height: MergeEngineUtilities.deviceBasedDynamicDimension(26, false, 1),
        marginLeft: MergeEngineUtilities.deviceBasedDynamicDimension(12, true, 1),
        marginTop: MergeEngineUtilities.deviceBasedDynamicDimension(8, false, 1),
        opacity: 1,
        backgroundColor: "transparent",
        fontStyle: "normal",
        fontWeight: "normal",
        includeFontPadding: false,
        padding: MergeEngineUtilities.deviceBasedDynamicDimension(0, true, 1),
        color: "rgba(53, 56, 72, 1)",
        textAlign: "left",
        textAlignVertical: "top",
        fontFamily: "",
        fontSize: MergeEngineUtilities.deviceBasedDynamicDimension(14, true, 1),
    },
    textlabel_SignupText: {
        position: "absolute",
        width: MergeEngineUtilities.deviceBasedDynamicDimension(110, true, 1),
        height: MergeEngineUtilities.deviceBasedDynamicDimension(39, false, 1),
        marginLeft: MergeEngineUtilities.deviceBasedDynamicDimension(140, true, 1),
        marginTop: MergeEngineUtilities.deviceBasedDynamicDimension(185, false, 1),
        opacity: 1,
        backgroundColor: "transparent",
        fontStyle: "normal",
        fontWeight: "normal",
        includeFontPadding: false,
        padding: MergeEngineUtilities.deviceBasedDynamicDimension(0, true, 1),
        color: "rgba(31, 69, 252, 1)",
        textAlign: "center",
        textAlignVertical: "top",
        fontFamily: "Poppins-Medium",
        fontSize: MergeEngineUtilities.deviceBasedDynamicDimension(28, true, 1),
    },
    group_Group3Group: {
        position: "relative",
        width: MergeEngineUtilities.deviceBasedDynamicDimension(27, true, 1),
        height: MergeEngineUtilities.deviceBasedDynamicDimension(26, false, 1),
        marginLeft: MergeEngineUtilities.deviceBasedDynamicDimension(15, true, 1),
        marginTop: MergeEngineUtilities.deviceBasedDynamicDimension(0, false, 1),
        opacity: 1,
        borderRadius: MergeEngineUtilities.deviceBasedDynamicDimension(0, true, 1),
        borderWidth: MergeEngineUtilities.deviceBasedDynamicDimension(0, true, 1),
    },
    textinput_TextFieldFilledLeadingIconNoAssistiveTextRestingWithIconSmallCopyTxtInput2: {
        position: "absolute",
        width: MergeEngineUtilities.deviceBasedDynamicDimension(96, true, 1),
        height: MergeEngineUtilities.deviceBasedDynamicDimension(40, false, 1),
        marginLeft: MergeEngineUtilities.deviceBasedDynamicDimension(152, true, 1),
        marginTop: MergeEngineUtilities.deviceBasedDynamicDimension(328, false, 1),
        opacity: 1,
        borderRadius: MergeEngineUtilities.deviceBasedDynamicDimension(8, true, 1),
        backgroundColor: "rgba(255, 255, 255, 1)",
    },
    attrbuted_textlabel_SelectACountryText: {
        position: "relative",
        width: MergeEngineUtilities.deviceBasedDynamicDimension(108, true, 1),
        height: MergeEngineUtilities.deviceBasedDynamicDimension(17, false, 1),
        marginLeft: MergeEngineUtilities.deviceBasedDynamicDimension(1, true, 1),
        marginTop: MergeEngineUtilities.deviceBasedDynamicDimension(0, false, 1),
        opacity: 1,
        backgroundColor: "transparent",
        fontStyle: "normal",
        fontWeight: "normal",
        includeFontPadding: false,
        padding: MergeEngineUtilities.deviceBasedDynamicDimension(0, true, 1),
        color: "rgba(53, 56, 72, 1)",
        textAlign: "center",
        textAlignVertical: "top",
        fontFamily: "",
        fontSize: MergeEngineUtilities.deviceBasedDynamicDimension(14, true, 1),
    },
    attrbuted_textlabel_DonthaveanaccounText2: {
        position: "relative",
        width: MergeEngineUtilities.deviceBasedDynamicDimension(252, true, 1),
        height: MergeEngineUtilities.deviceBasedDynamicDimension(22, false, 1),
        marginLeft: MergeEngineUtilities.deviceBasedDynamicDimension(69, true, 1),
        marginTop: MergeEngineUtilities.deviceBasedDynamicDimension(790, false, 1),
        opacity: 1,
        backgroundColor: "transparent",
        fontStyle: "normal",
        fontWeight: "normal",
        includeFontPadding: false,
        padding: MergeEngineUtilities.deviceBasedDynamicDimension(0, true, 1),
        color: "rgba(31, 69, 252, 1)",
        textAlign: "center",
        textAlignVertical: "top",
        fontFamily: "Poppins-Medium",
        fontSize: MergeEngineUtilities.deviceBasedDynamicDimension(14, true, 1),
    },
    textlabel_ChangePasswordText: {
        position: "absolute",
        width: MergeEngineUtilities.deviceBasedDynamicDimension(224, true, 1),
        height: MergeEngineUtilities.deviceBasedDynamicDimension(36, false, 1),
        marginLeft: MergeEngineUtilities.deviceBasedDynamicDimension(56, true, 1),
        marginTop: MergeEngineUtilities.deviceBasedDynamicDimension(69, false, 1),
        opacity: 1,
        backgroundColor: "transparent",
        fontStyle: "normal",
        fontWeight: "bold",
        includeFontPadding: false,
        padding: MergeEngineUtilities.deviceBasedDynamicDimension(0, true, 1),
        color: "rgba(17, 21, 28, 1)",
        textAlign: "left",
        textAlignVertical: "center",
        fontFamily: "Poppins-SemiBold",
        fontSize: MergeEngineUtilities.deviceBasedDynamicDimension(24, true, 1),
    },
    attrbuted_textlabel_DonthaveanaccounText: {
        position: "relative",
        width: MergeEngineUtilities.deviceBasedDynamicDimension(252, true, 1),
        height: MergeEngineUtilities.deviceBasedDynamicDimension(22, false, 1),
        marginLeft: MergeEngineUtilities.deviceBasedDynamicDimension(69, true, 1),
        marginTop: MergeEngineUtilities.deviceBasedDynamicDimension(790, false, 1),
        opacity: 1,
        backgroundColor: "transparent",
        fontStyle: "normal",
        fontWeight: "normal",
        includeFontPadding: false,
        padding: MergeEngineUtilities.deviceBasedDynamicDimension(0, true, 1),
        color: "rgba(92, 95, 97, 1)",
        textAlign: "center",
        textAlignVertical: "top",
        fontFamily: "Poppins-Medium",
        fontSize: MergeEngineUtilities.deviceBasedDynamicDimension(14, true, 1),
    },
    textlabel_SignInText: {
        position: "absolute",
        width: MergeEngineUtilities.deviceBasedDynamicDimension(101, true, 1),
        height: MergeEngineUtilities.deviceBasedDynamicDimension(39, false, 1),
        marginLeft: MergeEngineUtilities.deviceBasedDynamicDimension(144, true, 1),
        marginTop: MergeEngineUtilities.deviceBasedDynamicDimension(263, false, 1),
        opacity: 1,
        backgroundColor: "transparent",
        fontStyle: "normal",
        fontWeight: "normal",
        includeFontPadding: false,
        padding: MergeEngineUtilities.deviceBasedDynamicDimension(0, true, 1),
        color: "rgba(31, 69, 252, 1)",
        textAlign: "center",
        textAlignVertical: "top",
        fontFamily: "Poppins-Medium",
        fontSize: MergeEngineUtilities.deviceBasedDynamicDimension(28, true, 1),
    },
    attrbuted_SUBTITLE1COLORSTYLEText6: {
        position: "relative",
        width: MergeEngineUtilities.deviceBasedDynamicDimension(81, true, 1),
        height: MergeEngineUtilities.deviceBasedDynamicDimension(26, false, 1),
        marginLeft: MergeEngineUtilities.deviceBasedDynamicDimension(12, true, 1),
        marginTop: MergeEngineUtilities.deviceBasedDynamicDimension(8, false, 1),
        opacity: 1,
        backgroundColor: "transparent",
        fontStyle: "normal",
        fontWeight: "normal",
        includeFontPadding: false,
        padding: MergeEngineUtilities.deviceBasedDynamicDimension(0, true, 1),
        color: "rgba(53, 56, 72, 1)",
        textAlign: "left",
        textAlignVertical: "top",
        fontFamily: "",
        fontSize: MergeEngineUtilities.deviceBasedDynamicDimension(14, true, 1),
    },
    textinput_TextFieldFilledLeadingIconNoAssistiveTextRestingWithIconSmallCopyTxtInput3: {
        position: "absolute",
        width: MergeEngineUtilities.deviceBasedDynamicDimension(115, true, 1),
        height: MergeEngineUtilities.deviceBasedDynamicDimension(40, false, 1),
        marginLeft: MergeEngineUtilities.deviceBasedDynamicDimension(24, true, 1),
        marginTop: MergeEngineUtilities.deviceBasedDynamicDimension(488, false, 1),
        opacity: 1,
        borderRadius: MergeEngineUtilities.deviceBasedDynamicDimension(8, true, 1),
        backgroundColor: "rgba(255, 255, 255, 1)",
    },
    SUBTITLE1COLORSTYLEText8: {
        position: "absolute",
        width: MergeEngineUtilities.deviceBasedDynamicDimension(81, true, 0.7931034482758621),
        height: MergeEngineUtilities.deviceBasedDynamicDimension(26, false, 1),
        marginLeft: MergeEngineUtilities.deviceBasedDynamicDimension(12, true, 0.7931034482758621),
        marginTop: MergeEngineUtilities.deviceBasedDynamicDimension(8, false, 1),
        opacity: 1,
        backgroundColor: "transparent",
        fontStyle: "normal",
        fontWeight: "normal",
        includeFontPadding: false,
        padding: MergeEngineUtilities.deviceBasedDynamicDimension(0, true, 1),
        color: "rgba(53, 56, 72, 1)",
        textAlign: "left",
        textAlignVertical: "top",
        fontFamily: "",
        fontSize: MergeEngineUtilities.deviceBasedDynamicDimension(14, true, 1),
    },
    SUBTITLE1COLORSTYLEText16: {
        position: "absolute",
        width: MergeEngineUtilities.deviceBasedDynamicDimension(81, true, 0.7448275862068966),
        height: MergeEngineUtilities.deviceBasedDynamicDimension(26, false, 1),
        marginLeft: MergeEngineUtilities.deviceBasedDynamicDimension(12, true, 0.7448275862068966),
        marginTop: MergeEngineUtilities.deviceBasedDynamicDimension(8, false, 1),
        opacity: 1,
        backgroundColor: "transparent",
        fontStyle: "normal",
        fontWeight: "normal",
        includeFontPadding: false,
        padding: MergeEngineUtilities.deviceBasedDynamicDimension(0, true, 1),
        color: "rgba(53, 56, 72, 1)",
        textAlign: "left",
        textAlignVertical: "top",
        fontFamily: "",
        fontSize: MergeEngineUtilities.deviceBasedDynamicDimension(14, true, 1),
    },
    textlabel_SelectACountryText: {
        position: "relative",
        width: MergeEngineUtilities.deviceBasedDynamicDimension(108, true, 1),
        height: MergeEngineUtilities.deviceBasedDynamicDimension(17, false, 1),
        marginLeft: MergeEngineUtilities.deviceBasedDynamicDimension(1, true, 1),
        marginTop: MergeEngineUtilities.deviceBasedDynamicDimension(0, false, 1),
        opacity: 1,
        backgroundColor: "transparent",
        fontStyle: "normal",
        fontWeight: "normal",
        includeFontPadding: false,
        padding: MergeEngineUtilities.deviceBasedDynamicDimension(0, true, 1),
        color: "rgba(53, 56, 72, 1)",
        textAlign: "center",
        textAlignVertical: "top",
        fontFamily: "",
        fontSize: MergeEngineUtilities.deviceBasedDynamicDimension(14, true, 1),
    },
    SUBTITLE1COLORSTYLEText11: {
        position: "absolute",
        width: MergeEngineUtilities.deviceBasedDynamicDimension(81, true, 0.6206896551724138),
        height: MergeEngineUtilities.deviceBasedDynamicDimension(26, false, 1),
        marginLeft: MergeEngineUtilities.deviceBasedDynamicDimension(12, true, 0.6206896551724138),
        marginTop: MergeEngineUtilities.deviceBasedDynamicDimension(8, false, 1),
        opacity: 1,
        backgroundColor: "transparent",
        fontStyle: "normal",
        fontWeight: "normal",
        includeFontPadding: false,
        padding: MergeEngineUtilities.deviceBasedDynamicDimension(0, true, 1),
        color: "rgba(53, 56, 72, 1)",
        textAlign: "left",
        textAlignVertical: "top",
        fontFamily: "",
        fontSize: MergeEngineUtilities.deviceBasedDynamicDimension(14, true, 1),
    },
    attrbuted_SUBTITLE1COLORSTYLEText13: {
        position: "relative",
        width: MergeEngineUtilities.deviceBasedDynamicDimension(224, true, 1),
        height: MergeEngineUtilities.deviceBasedDynamicDimension(24, false, 1),
        marginLeft: MergeEngineUtilities.deviceBasedDynamicDimension(24, true, 1),
        marginTop: MergeEngineUtilities.deviceBasedDynamicDimension(16, false, 1),
        opacity: 1,
        backgroundColor: "transparent",
        fontStyle: "normal",
        fontWeight: "normal",
        includeFontPadding: false,
        padding: MergeEngineUtilities.deviceBasedDynamicDimension(0, true, 1),
        color: "rgba(53, 56, 72, 1)",
        textAlign: "left",
        textAlignVertical: "top",
        fontFamily: "",
        fontSize: MergeEngineUtilities.deviceBasedDynamicDimension(16, true, 1),
    },
    view_PathCopy2: {
        position: "absolute",
        width: MergeEngineUtilities.deviceBasedDynamicDimension(7, true, 1),
        height: MergeEngineUtilities.deviceBasedDynamicDimension(6, false, 1),
        marginLeft: MergeEngineUtilities.deviceBasedDynamicDimension(350, true, 1),
        marginTop: MergeEngineUtilities.deviceBasedDynamicDimension(588, false, 1),
        opacity: 1,
        backgroundColor: "rgba(240, 78, 54, 1)",
        borderRadius: MergeEngineUtilities.deviceBasedDynamicDimension(0, true, 1),
        borderWidth: MergeEngineUtilities.deviceBasedDynamicDimension(0, true, 1),
    },
    attrbuted_SUBTITLE1COLORSTYLEText4: {
        position: "relative",
        width: MergeEngineUtilities.deviceBasedDynamicDimension(224, true, 1),
        height: MergeEngineUtilities.deviceBasedDynamicDimension(24, false, 1),
        marginLeft: MergeEngineUtilities.deviceBasedDynamicDimension(24, true, 1),
        marginTop: MergeEngineUtilities.deviceBasedDynamicDimension(16, false, 1),
        opacity: 1,
        backgroundColor: "transparent",
        fontStyle: "normal",
        fontWeight: "normal",
        includeFontPadding: false,
        padding: MergeEngineUtilities.deviceBasedDynamicDimension(0, true, 1),
        color: "rgba(53, 56, 72, 1)",
        textAlign: "left",
        textAlignVertical: "top",
        fontFamily: "",
        fontSize: MergeEngineUtilities.deviceBasedDynamicDimension(16, true, 1),
    },
    textinput_TextFieldFilledLeadingIconNoAssistiveTextRestingWithIconSmallCopyTxtInput: {
        position: "absolute",
        width: MergeEngineUtilities.deviceBasedDynamicDimension(111, true, 1),
        height: MergeEngineUtilities.deviceBasedDynamicDimension(40, false, 1),
        marginLeft: MergeEngineUtilities.deviceBasedDynamicDimension(127, true, 1),
        marginTop: MergeEngineUtilities.deviceBasedDynamicDimension(168, false, 1),
        opacity: 1,
        borderRadius: MergeEngineUtilities.deviceBasedDynamicDimension(8, true, 1),
        backgroundColor: "rgba(255, 255, 255, 1)",
    },
    view_Rectangle13Copy3: {
        position: "absolute",
        width: MergeEngineUtilities.deviceBasedDynamicDimension(391, true, 1),
        height: MergeEngineUtilities.deviceBasedDynamicDimension(78, false, 1),
        marginLeft: MergeEngineUtilities.deviceBasedDynamicDimension(0, true, 1),
        marginTop: MergeEngineUtilities.deviceBasedDynamicDimension(48, false, 1),
        opacity: 1,
        backgroundColor: "rgba(255, 255, 255, 1)",
        borderRadius: MergeEngineUtilities.deviceBasedDynamicDimension(0, true, 1),
        borderWidth: MergeEngineUtilities.deviceBasedDynamicDimension(0, true, 1),
    },
    SUBTITLE1COLORSTYLEText10: {
        position: "absolute",
        width: MergeEngineUtilities.deviceBasedDynamicDimension(224, true, 1.0426829268292683),
        height: MergeEngineUtilities.deviceBasedDynamicDimension(24, false, 1),
        marginLeft: MergeEngineUtilities.deviceBasedDynamicDimension(24, true, 1.0426829268292683),
        marginTop: MergeEngineUtilities.deviceBasedDynamicDimension(16, false, 1),
        opacity: 1,
        backgroundColor: "transparent",
        fontStyle: "normal",
        fontWeight: "normal",
        includeFontPadding: false,
        padding: MergeEngineUtilities.deviceBasedDynamicDimension(0, true, 1),
        color: "rgba(53, 56, 72, 1)",
        textAlign: "left",
        textAlignVertical: "top",
        fontFamily: "",
        fontSize: MergeEngineUtilities.deviceBasedDynamicDimension(16, true, 1),
    },
    attrbuted_SUBTITLE1COLORSTYLEText8: {
        position: "relative",
        width: MergeEngineUtilities.deviceBasedDynamicDimension(81, true, 1),
        height: MergeEngineUtilities.deviceBasedDynamicDimension(26, false, 1),
        marginLeft: MergeEngineUtilities.deviceBasedDynamicDimension(12, true, 1),
        marginTop: MergeEngineUtilities.deviceBasedDynamicDimension(8, false, 1),
        opacity: 1,
        backgroundColor: "transparent",
        fontStyle: "normal",
        fontWeight: "normal",
        includeFontPadding: false,
        padding: MergeEngineUtilities.deviceBasedDynamicDimension(0, true, 1),
        color: "rgba(53, 56, 72, 1)",
        textAlign: "left",
        textAlignVertical: "top",
        fontFamily: "",
        fontSize: MergeEngineUtilities.deviceBasedDynamicDimension(14, true, 1),
    },
    textlabel_SelectLanguageText: {
        position: "absolute",
        width: MergeEngineUtilities.deviceBasedDynamicDimension(104, true, 1),
        height: MergeEngineUtilities.deviceBasedDynamicDimension(17, false, 1),
        marginLeft: MergeEngineUtilities.deviceBasedDynamicDimension(24, true, 1),
        marginTop: MergeEngineUtilities.deviceBasedDynamicDimension(394, false, 1),
        opacity: 1,
        backgroundColor: "transparent",
        fontStyle: "normal",
        fontWeight: "normal",
        includeFontPadding: false,
        padding: MergeEngineUtilities.deviceBasedDynamicDimension(0, true, 1),
        color: "rgba(53, 56, 72, 1)",
        textAlign: "left",
        textAlignVertical: "top",
        fontFamily: "",
        fontSize: MergeEngineUtilities.deviceBasedDynamicDimension(14, true, 1),
    },
    textinput_TextFieldFilledLeadingIconNoAssistiveTextRestingWithIconSmallCopyCopyTxtInput: {
        position: "absolute",
        width: MergeEngineUtilities.deviceBasedDynamicDimension(96, true, 1),
        height: MergeEngineUtilities.deviceBasedDynamicDimension(40, false, 1),
        marginLeft: MergeEngineUtilities.deviceBasedDynamicDimension(152, true, 1),
        marginTop: MergeEngineUtilities.deviceBasedDynamicDimension(488, false, 1),
        opacity: 1,
        borderRadius: MergeEngineUtilities.deviceBasedDynamicDimension(8, true, 1),
        backgroundColor: "rgba(255, 255, 255, 1)",
    },
    textlabel_DonthaveanaccounText: {
        position: "absolute",
        width: MergeEngineUtilities.deviceBasedDynamicDimension(252, true, 1),
        height: MergeEngineUtilities.deviceBasedDynamicDimension(22, false, 1),
        marginLeft: MergeEngineUtilities.deviceBasedDynamicDimension(69, true, 1),
        marginTop: MergeEngineUtilities.deviceBasedDynamicDimension(790, false, 1),
        opacity: 1,
        backgroundColor: "transparent",
        fontStyle: "normal",
        fontWeight: "normal",
        includeFontPadding: false,
        padding: MergeEngineUtilities.deviceBasedDynamicDimension(0, true, 1),
        color: "rgba(92, 95, 97, 1)",
        textAlign: "center",
        textAlignVertical: "top",
        fontFamily: "Poppins-Medium",
        fontSize: MergeEngineUtilities.deviceBasedDynamicDimension(14, true, 1),
    },
    group_GroupGroup2: {
        position: "relative",
        width: MergeEngineUtilities.deviceBasedDynamicDimension(343, true, 1),
        height: MergeEngineUtilities.deviceBasedDynamicDimension(56, false, 1),
        marginLeft: MergeEngineUtilities.deviceBasedDynamicDimension(-197, true, 1),
        marginTop: MergeEngineUtilities.deviceBasedDynamicDimension(26, false, 1),
        opacity: 1,
        borderRadius: MergeEngineUtilities.deviceBasedDynamicDimension(0, true, 1),
        borderWidth: MergeEngineUtilities.deviceBasedDynamicDimension(0, true, 1),
    },
    textinput_TextFieldFilledLeadingIconNoAssistiveTextRestingCopy5CopyTxtInput: {
        position: "absolute",
        width: MergeEngineUtilities.deviceBasedDynamicDimension(342, true, 1),
        height: MergeEngineUtilities.deviceBasedDynamicDimension(56, false, 1),
        marginLeft: MergeEngineUtilities.deviceBasedDynamicDimension(24, true, 1),
        marginTop: MergeEngineUtilities.deviceBasedDynamicDimension(740, false, 1),
        opacity: 1,
        borderRadius: MergeEngineUtilities.deviceBasedDynamicDimension(8, true, 1),
        backgroundColor: "rgba(255, 255, 255, 1)",
    },
    view_PathCopy22: {
        position: "absolute",
        width: MergeEngineUtilities.deviceBasedDynamicDimension(7, true, 1),
        height: MergeEngineUtilities.deviceBasedDynamicDimension(6, false, 1),
        marginLeft: MergeEngineUtilities.deviceBasedDynamicDimension(350, true, 1),
        marginTop: MergeEngineUtilities.deviceBasedDynamicDimension(748, false, 1),
        opacity: 1,
        backgroundColor: "rgba(240, 78, 54, 1)",
        borderRadius: MergeEngineUtilities.deviceBasedDynamicDimension(0, true, 1),
        borderWidth: MergeEngineUtilities.deviceBasedDynamicDimension(0, true, 1),
    },
    SUBTITLE1COLORSTYLEText14: {
        position: "absolute",
        width: MergeEngineUtilities.deviceBasedDynamicDimension(81, true, 0.7931034482758621),
        height: MergeEngineUtilities.deviceBasedDynamicDimension(26, false, 1),
        marginLeft: MergeEngineUtilities.deviceBasedDynamicDimension(12, true, 0.7931034482758621),
        marginTop: MergeEngineUtilities.deviceBasedDynamicDimension(8, false, 1),
        opacity: 1,
        backgroundColor: "transparent",
        fontStyle: "normal",
        fontWeight: "normal",
        includeFontPadding: false,
        padding: MergeEngineUtilities.deviceBasedDynamicDimension(0, true, 1),
        color: "rgba(53, 56, 72, 1)",
        textAlign: "left",
        textAlignVertical: "top",
        fontFamily: "",
        fontSize: MergeEngineUtilities.deviceBasedDynamicDimension(14, true, 1),
    },
    SUBTITLE1COLORSTYLEText6: {
        position: "absolute",
        width: MergeEngineUtilities.deviceBasedDynamicDimension(81, true, 0.6620689655172414),
        height: MergeEngineUtilities.deviceBasedDynamicDimension(26, false, 1),
        marginLeft: MergeEngineUtilities.deviceBasedDynamicDimension(12, true, 0.6620689655172414),
        marginTop: MergeEngineUtilities.deviceBasedDynamicDimension(8, false, 1),
        opacity: 1,
        backgroundColor: "transparent",
        fontStyle: "normal",
        fontWeight: "normal",
        includeFontPadding: false,
        padding: MergeEngineUtilities.deviceBasedDynamicDimension(0, true, 1),
        color: "rgba(53, 56, 72, 1)",
        textAlign: "left",
        textAlignVertical: "top",
        fontFamily: "",
        fontSize: MergeEngineUtilities.deviceBasedDynamicDimension(14, true, 1),
    },
    attrbuted_textlabel_SelectMediaHouseText: {
        position: "relative",
        width: MergeEngineUtilities.deviceBasedDynamicDimension(137, true, 1),
        height: MergeEngineUtilities.deviceBasedDynamicDimension(20, false, 1),
        marginLeft: MergeEngineUtilities.deviceBasedDynamicDimension(24, true, 1),
        marginTop: MergeEngineUtilities.deviceBasedDynamicDimension(554, false, 1),
        opacity: 1,
        backgroundColor: "transparent",
        fontStyle: "normal",
        fontWeight: "normal",
        includeFontPadding: false,
        padding: MergeEngineUtilities.deviceBasedDynamicDimension(0, true, 1),
        color: "rgba(53, 56, 72, 1)",
        textAlign: "left",
        textAlignVertical: "top",
        fontFamily: "Poppins-Regular",
        fontSize: MergeEngineUtilities.deviceBasedDynamicDimension(14, true, 1),
    },
    textinput_TextFieldFilledLeadingIconNoAssistiveTextRestingWithIconSmallCopyCopy2TxtInput: {
        position: "absolute",
        width: MergeEngineUtilities.deviceBasedDynamicDimension(121, true, 1),
        height: MergeEngineUtilities.deviceBasedDynamicDimension(40, false, 1),
        marginLeft: MergeEngineUtilities.deviceBasedDynamicDimension(127, true, 1),
        marginTop: MergeEngineUtilities.deviceBasedDynamicDimension(648, false, 1),
        opacity: 1,
        borderRadius: MergeEngineUtilities.deviceBasedDynamicDimension(8, true, 1),
        backgroundColor: "rgba(255, 255, 255, 1)",
    },
    group_Group3CopyGroup: {
        position: "absolute",
        width: MergeEngineUtilities.deviceBasedDynamicDimension(69, true, 1),
        height: MergeEngineUtilities.deviceBasedDynamicDimension(26, false, 1),
        marginLeft: MergeEngineUtilities.deviceBasedDynamicDimension(161, true, 1),
        marginTop: MergeEngineUtilities.deviceBasedDynamicDimension(894, false, 1),
        opacity: 1,
        borderRadius: MergeEngineUtilities.deviceBasedDynamicDimension(0, true, 1),
        borderWidth: MergeEngineUtilities.deviceBasedDynamicDimension(0, true, 1),
    },
    SUBTITLE1COLORSTYLEText9: {
        position: "absolute",
        width: MergeEngineUtilities.deviceBasedDynamicDimension(81, true, 0.6620689655172414),
        height: MergeEngineUtilities.deviceBasedDynamicDimension(26, false, 1),
        marginLeft: MergeEngineUtilities.deviceBasedDynamicDimension(12, true, 0.6620689655172414),
        marginTop: MergeEngineUtilities.deviceBasedDynamicDimension(8, false, 1),
        opacity: 1,
        backgroundColor: "transparent",
        fontStyle: "normal",
        fontWeight: "normal",
        includeFontPadding: false,
        padding: MergeEngineUtilities.deviceBasedDynamicDimension(0, true, 1),
        color: "rgba(53, 56, 72, 1)",
        textAlign: "left",
        textAlignVertical: "top",
        fontFamily: "",
        fontSize: MergeEngineUtilities.deviceBasedDynamicDimension(14, true, 1),
    },
    attrbuted_SUBTITLE1COLORSTYLEText7: {
        position: "relative",
        width: MergeEngineUtilities.deviceBasedDynamicDimension(224, true, 1),
        height: MergeEngineUtilities.deviceBasedDynamicDimension(24, false, 1),
        marginLeft: MergeEngineUtilities.deviceBasedDynamicDimension(24, true, 1),
        marginTop: MergeEngineUtilities.deviceBasedDynamicDimension(16, false, 1),
        opacity: 1,
        backgroundColor: "transparent",
        fontStyle: "normal",
        fontWeight: "normal",
        includeFontPadding: false,
        padding: MergeEngineUtilities.deviceBasedDynamicDimension(0, true, 1),
        color: "rgba(53, 56, 72, 1)",
        textAlign: "left",
        textAlignVertical: "top",
        fontFamily: "",
        fontSize: MergeEngineUtilities.deviceBasedDynamicDimension(16, true, 1),
    },
    SUBTITLE1COLORSTYLEText13: {
        position: "absolute",
        width: MergeEngineUtilities.deviceBasedDynamicDimension(224, true, 1.0426829268292683),
        height: MergeEngineUtilities.deviceBasedDynamicDimension(24, false, 1),
        marginLeft: MergeEngineUtilities.deviceBasedDynamicDimension(24, true, 1.0426829268292683),
        marginTop: MergeEngineUtilities.deviceBasedDynamicDimension(16, false, 1),
        opacity: 1,
        backgroundColor: "transparent",
        fontStyle: "normal",
        fontWeight: "normal",
        includeFontPadding: false,
        padding: MergeEngineUtilities.deviceBasedDynamicDimension(0, true, 1),
        color: "rgba(53, 56, 72, 1)",
        textAlign: "left",
        textAlignVertical: "top",
        fontFamily: "",
        fontSize: MergeEngineUtilities.deviceBasedDynamicDimension(16, true, 1),
    },
    button_ButtonsContainedEnabledCopyButton: {
        position: "absolute",
        width: MergeEngineUtilities.deviceBasedDynamicDimension(342, true, 1),
        height: MergeEngineUtilities.deviceBasedDynamicDimension(56, false, 1),
        marginLeft: MergeEngineUtilities.deviceBasedDynamicDimension(24, true, 1),
        marginTop: MergeEngineUtilities.deviceBasedDynamicDimension(952, false, 1),
        opacity: 1,
        backgroundColor: "rgba(31, 69, 252, 1)",
        borderRadius: MergeEngineUtilities.deviceBasedDynamicDimension(8, true, 1),
        justifyContent: "center",
    },
    SUBTITLE1COLORSTYLEText4: {
        position: "absolute",
        width: MergeEngineUtilities.deviceBasedDynamicDimension(224, true, 1.0426829268292683),
        height: MergeEngineUtilities.deviceBasedDynamicDimension(24, false, 1),
        marginLeft: MergeEngineUtilities.deviceBasedDynamicDimension(24, true, 1.0426829268292683),
        marginTop: MergeEngineUtilities.deviceBasedDynamicDimension(16, false, 1),
        opacity: 1,
        backgroundColor: "transparent",
        fontStyle: "normal",
        fontWeight: "normal",
        includeFontPadding: false,
        padding: MergeEngineUtilities.deviceBasedDynamicDimension(0, true, 1),
        color: "rgba(53, 56, 72, 1)",
        textAlign: "left",
        textAlignVertical: "top",
        fontFamily: "",
        fontSize: MergeEngineUtilities.deviceBasedDynamicDimension(16, true, 1),
    },
    textlabel_SelectCategoriesCopyText: {
        position: "absolute",
        width: MergeEngineUtilities.deviceBasedDynamicDimension(115, true, 1),
        height: MergeEngineUtilities.deviceBasedDynamicDimension(17, false, 1),
        marginLeft: MergeEngineUtilities.deviceBasedDynamicDimension(24, true, 1),
        marginTop: MergeEngineUtilities.deviceBasedDynamicDimension(714, false, 1),
        opacity: 1,
        backgroundColor: "transparent",
        fontStyle: "normal",
        fontWeight: "normal",
        includeFontPadding: false,
        padding: MergeEngineUtilities.deviceBasedDynamicDimension(0, true, 1),
        color: "rgba(53, 56, 72, 1)",
        textAlign: "left",
        textAlignVertical: "top",
        fontFamily: "",
        fontSize: MergeEngineUtilities.deviceBasedDynamicDimension(14, true, 1),
    },
    group_Group2CopyGroup: {
        position: "relative",
        width: MergeEngineUtilities.deviceBasedDynamicDimension(27, true, 1),
        height: MergeEngineUtilities.deviceBasedDynamicDimension(26, false, 1),
        marginLeft: MergeEngineUtilities.deviceBasedDynamicDimension(15, true, 1),
        marginTop: MergeEngineUtilities.deviceBasedDynamicDimension(0, false, 1),
        opacity: 1,
        borderRadius: MergeEngineUtilities.deviceBasedDynamicDimension(0, true, 1),
        borderWidth: MergeEngineUtilities.deviceBasedDynamicDimension(0, true, 1),
    },
    attrbuted_SUBTITLE1COLORSTYLEText14: {
        position: "relative",
        width: MergeEngineUtilities.deviceBasedDynamicDimension(81, true, 1),
        height: MergeEngineUtilities.deviceBasedDynamicDimension(26, false, 1),
        marginLeft: MergeEngineUtilities.deviceBasedDynamicDimension(12, true, 1),
        marginTop: MergeEngineUtilities.deviceBasedDynamicDimension(8, false, 1),
        opacity: 1,
        backgroundColor: "transparent",
        fontStyle: "normal",
        fontWeight: "normal",
        includeFontPadding: false,
        padding: MergeEngineUtilities.deviceBasedDynamicDimension(0, true, 1),
        color: "rgba(53, 56, 72, 1)",
        textAlign: "left",
        textAlignVertical: "top",
        fontFamily: "",
        fontSize: MergeEngineUtilities.deviceBasedDynamicDimension(14, true, 1),
    },
    textinput_TextFieldFilledLeadingIconNoAssistiveTextRestingWithIconSmallTxtInput: {
        position: "absolute",
        width: MergeEngineUtilities.deviceBasedDynamicDimension(90, true, 1),
        height: MergeEngineUtilities.deviceBasedDynamicDimension(40, false, 1),
        marginLeft: MergeEngineUtilities.deviceBasedDynamicDimension(24, true, 1),
        marginTop: MergeEngineUtilities.deviceBasedDynamicDimension(168, false, 1),
        opacity: 1,
        borderRadius: MergeEngineUtilities.deviceBasedDynamicDimension(8, true, 1),
        backgroundColor: "rgba(255, 255, 255, 1)",
    },
    attrbuted_textlabel_SignupText: {
        position: "relative",
        width: MergeEngineUtilities.deviceBasedDynamicDimension(110, true, 1),
        height: MergeEngineUtilities.deviceBasedDynamicDimension(39, false, 1),
        marginLeft: MergeEngineUtilities.deviceBasedDynamicDimension(140, true, 1),
        marginTop: MergeEngineUtilities.deviceBasedDynamicDimension(185, false, 1),
        opacity: 1,
        backgroundColor: "transparent",
        fontStyle: "normal",
        fontWeight: "normal",
        includeFontPadding: false,
        padding: MergeEngineUtilities.deviceBasedDynamicDimension(0, true, 1),
        color: "rgba(31, 69, 252, 1)",
        textAlign: "center",
        textAlignVertical: "top",
        fontFamily: "Poppins-Medium",
        fontSize: MergeEngineUtilities.deviceBasedDynamicDimension(28, true, 1),
    },
    attrbuted_TEXTCOLORSTYLEText: {
        position: "relative",
        width: MergeEngineUtilities.deviceBasedDynamicDimension(64, true, 1),
        height: MergeEngineUtilities.deviceBasedDynamicDimension(16, false, 1),
        marginLeft: MergeEngineUtilities.deviceBasedDynamicDimension(16, true, 1),
        marginTop: MergeEngineUtilities.deviceBasedDynamicDimension(10, false, 1),
        opacity: 1,
        backgroundColor: "transparent",
        fontStyle: "normal",
        fontWeight: "normal",
        includeFontPadding: false,
        padding: MergeEngineUtilities.deviceBasedDynamicDimension(0, true, 1),
        color: "rgba(255, 255, 255, 1)",
        textAlign: "center",
        textAlignVertical: "top",
        fontFamily: "AirbnbCerealApp-Medium",
        fontSize: MergeEngineUtilities.deviceBasedDynamicDimension(16, true, 1),
    },
})

export default global_styles;
// Customizable Area End